const imageList = {
    'Action': 'ACTION.jpg',
    'Adventure': 'ADVENTURE.jpg',
    'Animation': 'ANIMATION.jpg',
    'Comedy': 'COMEDY.jpg',
    'Crime': 'CRIME.jpg',
    'Documentary': 'DOCUMENTARY.jpg',
    'Drama': 'DRAMA.jpg',
    'Family': 'FAMILY.jpg',
    'Fantasy': 'FANTASY.jpg',
    'History': 'HISTORY.jpg',
    'Horror': 'HORROR.jpg',
    'Music': 'MUSIC.jpg',
    'Mystery': 'MYSTERY.jpg',
    'Romance': 'ROMANCE.jpg',
    'Science Fiction': 'SCIENCE.jpg',
    'TV Movie': 'TVMOVIE.jpg',
    'Thriller': 'THRILLER.jfif',
    'War': 'WAR.jpg',
    'Western': 'WESTERN.jpg',
    'Action & Adventure': 'ADVENTURE.jpg',
    'Kids': 'KIDS.jfif',
    'News': 'NEWS.jpg',
    'Reality': 'REALITY.jpg',
    'Sci-Fi & Fantasy': 'SCIENCE.jpg',
    'Soap': 'SOAP.jpg',
    'Talk': 'TALK.jpg',
    'War & Politics': 'WAR.jpg'
};

module.exports = imageList;